#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/mk?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver

#
springbootdev:
  prop:
    upload-domain: http://localhost:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: z:/html
    log-mode: true
  mybatis-plus:
    sql-log:
      enable: false
