#服务器端口
server:
  port: 8108

#数据源配置
spring:
  datasource:
    url: ${springclouddev.datasource.test.url}
    username: ${springclouddev.datasource.test.username}
    password: ${springclouddev.datasource.test.password}
# apollo的配置
# 对应 Apollo 中应用的 AppId
app:
  id: 100001
apollo:
  bootstrap:
    enabled: true
    # 添加 application 本身 和 TEST1.Common Namespace 的配置
    namespaces: application,TEST1.Common