#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${springclouddev.datasource.test.url}
    username: ${springclouddev.datasource.test.username}
    password: ${springclouddev.datasource.test.password}
